=head1 Krang Build System

The Krang build system is used to build Krang distributions.  A Krang
distribution consists of the following pieces:

=over 4

=item 1

Krang source files, including Perl modules and scripts, SQL, XML
Schemas and templates

=item 2

Required CPAN modules compiled and installed into F<lib/>

=item 3

Apache, compiled and installed into F<apache/>

=item 4

The krang_install script configured with platform-appropriate defaults

=back

Krang distributions are created to work on a specific platform with a
specific version of Perl.  For example, typical distribution filenames
might be:

  krang-1.001-Redhat7.3-perl5.6.1-i686-linux.tar.gz
  krang-1.001-Redhat9-perl5.8.2-i686-linux.tar.gz

The build system will supply the distribution name (Redhat9,
Redhat7.3, etc) and Perl will provide the Perl version and
architecture using:

  perl -MConfig -e 'printf "perl%d.%d.%d-%s",
                    (map { ord($_) } split("", $^V, 3)), $Config{archname}'

End-users must choose the distribution that matches their platform,
although the installer will check to make sure they made a reasonable
choice.

A special source distribution is made without building platform
binaries.  Users of this distribution will need to use the Krang build
system to produce a distribution they can install.

=head2 C<krang_build>

To generate a build for a platform, run the C<krang_build> script with
at least one argument - C<--platform>:

  krang_build --platform Redhat7.3

This will cause the build system to use the platform build resources
in platform/Redhat7.3.  If all goes well the final line of output
should be something like:

   Build finished, created krang-1.001-Redhat7.3-perl5.6.1-i686-linux.tar.gz

=head2 Krang::Build

The L<Krang::Build> module will serve as a base-class for all platform
build modules.
