=head1 Krang Changelog

This document contains a list of changes for each release of Krang.

=head2 v1.016 - Under Development

=over

=item *

Added Krang::User creation/destruction to Krang::Test::Content -
furthering the goal that Krang::Test::Content should be able to create
all parts of a site randomly, and clean up everything properly at the
end. [Peter]

=item *

Modified Krang::Contrib::deserialize_xml() to create contributor types
as needed.  [Sam]

=item *

Changed Krang::ElementClass::Date to store and load data in XML using
an ISO-8601 date-time format. Also added missing template_data()
method.  [Sam]

=item *

Added support for Debian. [Jason Purdy]

=item *

Fixed bug where clicking on a media link in the element editor would
open a new window every time. [Sam]

=item *

Moved code to run tests from Makefile into bin/krang_test.  This
allows krang_install to affect which Perl binary runs the tests. It
also helps with BSD portability since the test target didn't work with
BSD make. [Sam]

=back

=head2 v1.015 - April 8, 2004

=over

=item *

Added a message to remind users that they must create a site before
adding stories, media or templates. [Sam]

=item *

Added initial support for FreeBSD!  Currently it only supports FreeBSD
5.2.1 with GNU make (gmake) installed, as that was the only available
testable environment.  Would be nice if someone with more experience
in BSD Makefiles could get Krang's Makefiles to work with BSD make.
There should be nothing keeping Krang from working with earlier
versions of FreeBSD, but that will require someone to pick up the BSD
ball and run with it.  [Peter]

=item *

Fixed site editor to check that URLs don't have paths attached to them
and that paths are obsolute. [Sam]

=item *

Fixed krang_upgrade to use Krang::Platform.  Added a new method to
Krang::Platform, post_upgrade_message(). [Sam]

=item *

Upgraded XML-Writer, HTML-Parser, and Tar-Archive to get rid of warnings.
[Perrin]

=item *

Upgraded mod_perl and apache to latest releases. [Perrin]

=item *

Fixed the behavior of Krang::Publisher->preview_story().  Following
the original spec, it now writes the story out to all categories in
the preview path.  Fixed Krang::Story->preview_path as well. [Peter]

=item *

Upgraded Test::Harness to 2.40 to enable warnings during tests.  Fixed
a number of warnings in the test files. [Perrin] [Sam]

=item *

Fixed bug where schedule tests would fail frequently due to
krang_schedulectl leaving bad PID files around.  Also made the
schedule tests quiet unless an error occurs. [Sam]

=item *

Fixed a bug where using a category_trail_loop in a category element
template produced an ISE. [Sam]

=item *

Added support for Fedora Core 1. [Perrin Harkins]

=item *

Moved Krang user/group creation from krang_install to Krang::Platform.
This can now be overridden on a platform-by-platform basis. [Peter]

=item *

Created Krang::Platform->find_bin().  Use of this sub now needs to be
propegated throughout krang_install along with Krang::Platform and its
derivatives - it searches $PATH for the full path for the executable
you're trying to run. [Peter]



=item *

Moved the final installation message out of bin/krang_install, created
Krang::Platform->post_install_message() that generates the same output.
This can now be overridden & extended on a platform-specific basis. [Peter]

=item *

Split the various checks out of Krang::Platform->verify_dependencies().
This will simplify ports to other platforms, as individual checks can
now be overridden, rather than the entire sub. [Peter]

=item *

Added new default scheduled job to analyze DB tables nightly.  This
greatly improves performance for large databases. [Sam]

=item *

Fixed bug where default scheduled jobs (tmp cleaner and session
expiration) weren't being run for new installations. [Sam]

=item *

Fixed krang_createdb to stop after the first failed system
call. [Scott Lanning]

=item *

Added enhanced cache debugging code and a last-resort check in an
Apache log_handler to make sure the cache is off at the end of the
request. [Sam]

=item *

Moved setup of /etc/init.d link from krang_install into the Redhat
platform modules' finish_installation() methods.  This should allow
the Gentoo and Debian ports to proceed. [Sam]

=item *

Fixed build and installation system to work with a Perl that isn't
called 'perl' and in your path.  So, for example, if you've got a
binary called 'perl5.8.0' you can build Krang with it and install with
it. [Sam]

=item *

Added initial support for Gentoo 1.4.3. [Peter]

=item *

Updated porting.pod with steps that might really work. [Sam]

=item *

Fixed a bug where an error occuring during preview triggered a
Krang::Cache error which corrupted the display. [Sam]

=item *

Improved error message generated when InstanceElementSet is set to an
element set that isn't installed. [Peter]

=item *

Fixed a ton of whitespace in module source files which was breaking
the POD output. [Peter]

=back

=head2 v1.014 - March 31, 2004

=over

=item *

First public release of Krang!

=back
