=head1 Krang Changelog

This document contains a list of changes for each release of Krang.

=head2 v1.027 - Under Development

=over

=item *

Bugfix in L<Krang::Schedule> - alerts were not being run because 
of some incomplete code meant to check for valid alert id. [Matt]

=item * 

Made changes in media UI to:

1. add 'publish to preview' button and underlying functionality
2. cause 'publish' button in edit screen to also preview the media
3. remove the 'reset' button.
4. have the 'Publish' button appear on the new media screen, no need to 
have to click save first. [Matt]

=item *

Small bugfix to the Solaris C<Platform.pm> [Joseph Sacco]

=item *

C<bin/krang_upgrade> now supports remote MySQL databases.  [Aaron
Ross]

=item *

Bugfix for C<bin/krang_publish>, now correctly counts media total
and time with --to-preview option. [Matt]

=item *

Added C<bin/krang_expunge> - designed to work in conjunction with
C<bin/krang_extract_subset>, it deletes a site from a multi-site Krang
instance, and ensures that no dependencies are left hanging. [Peter]

=item *

Minor bugfix in C<bin/krang_extract_subset> - proper handling of
StoryLink/MediaLink elements that do not point to anything.

=back


=head2 v1.026 - November 4, 2004

=over

=item *

Re-generated templates.kds for the Default and Tutorial element
libraries, making them architecture-independent (see nfreeze note
below).  [Peter]

=item *

Krang now uses C<Storable::nfreeze> rather than C<Storable::freeze>
when saving binary and object data.  The move to C<nfreeze> should
make .kds files architecture-independent, allowing migrations between
different platforms (e.g. x86 / SPARC / PPC).  [Peter]

=item *

Updated L<Storable> to the current release, version 2.13.  [Peter]

=item *

Added C<bin/krang_extract_subset>.  This script is designed to extract
a single site and its' content from a multi-site Krang Instance.
[Peter]

=item *

L<Krang::Story> now handles calls to find() with an arrayref of
site_ids. [Peter]

=item *

L<Krang::Media> now handles calls to find() with an arrayref of
site_ids. [Peter]

=item *

L<Krang::Template> now handles calls to find() with an arrayref of
category_ids. [Peter]

=item * 

Fixed a bug in L<Krang::CGI::Site> that would cause ISE on attempted 
delete if a site had content in its root directory but no had no
other categories [Matt]

=item *

Added population of 'width', 'height', and 'image_dimensions' for 
Krang::ElementClass::MediaLink fill_template. [Matt]

=item *

Bugfixes to L<Krang::CGI::Template> that prevented files from being
uploaded to the edit template screen, and caused ISE when no filename
present. [Matt]

=item *

Bugfixes to L<Krang::Schedule> - checked out or missing objects will
no longer drop large perl-heavy error messages in the logs.  Thanks
for Michael Peters for the initial work to fix it.  [Peter]

=item *

Fixed a bug in L<Krang::Publisher> - zero-length story output is now
output properly, with a logfile entry to make a note of it.  [Peter]

=item *

Deployed version is now displayed in the template edit UI.
[Michael Peters]

=item *

Fixed a bug in L<Krang::Schedule> - scheduling specific versions of a
story or media object for publish now works again.  [Peter]

=item *

Additional documentation!  The long-awaited 
HREF[Creating an Element Library in Krang|building_element_library.html]! [Peter]


=item *

New documentation added -
HREF[Running Krang on the Desktop|krang_on_desktop.html]:
A guide on how to install and run Krang on your local machine.
[Peter]

=item *

Solaris support added!  Tested against Solaris 9, this should also
work against previous versions as well.  Thanks to Joseph Sacco
(jsacco@earthlink.net). [Peter]

=item *

Support for Mac OSX has been added!  Currently tested against 10.3.5,
let us know if it works on other versions!  Thanks to Matthew Wood
(matt@nomorefluffybunny.com).  [Peter]

=item *

C<bin/krang_info> now gives story/media stats for each
instance. [Peter]

=item *

Fixed a bug in L<Krang::ElementClass::StoryLink> where elements that
were never linked to stories no longer throw an error, but return
cleanly.  [Michael Peters]

=item *

Mandrake support has been added!  [Matt]

=item *

Fixed browser detection to deal with 1.0 prerelease of Firefox, which
gives a version number of 0.10.  [Aaron Ross]

=back

=head2 v1.025 - October 1, 2004

=over

=item *

Cleaned up error handling in L<Krang::Publisher> and the
C<bin/krang_publish> script - errors are now trapped properly and
reported in a cleaner fashion.  [Peter]

=item *

Fixed a bug in the upgrade process of 1.024.  Users who upgraded to
1.024 should immediately upgrade to 1.025.  [Peter]

=item *

C<bin/krang_publish> and C<bin/krang_delete> now properly interact
with hidden stories. [Peter]

=back


=head2 v1.024 - September 24, 2004

=over

=item *

Send HTTP header with root menu. [Aaron Ross]

=item *

Escape values on login page to foil cross-site scripting attacks. [Perrin]

=item *

Add option to show 100 results per page. [Perrin]

=item *

Restructured the index page in docs/ - added a 'User' section, moved a
few things around to make things easier for new users. [Peter]

=item *

Added C<bin/krang_info> - a simple command-line script to list the
currently configured status of Krang.  [Peter]

=item *

Reordered subroutine exports in L<Krang::Element> to fix a library
loading loop that cropped up under some circumstances.  Thanks to
Michael Peters (mpeters@plusthree.com) for finding it.  [Peter]


=item *

Added support for hidden stories, based on class definitions.  A
hidden story is one that, by default, does not show up in calls to
C<find()>.  This is useful for auto-generated story lists where some
types of stories shouldn't be listed.  For example, this will be used
immediately by HREF[Krang Sitemap|/addons.html] and 
HREF[Krang RSS|/addons.html], neither of which should show in most lists.  See
L<Krang::ElementClass::TopLevel> and L<Krang::Story> for more
information.  [Peter]

=item *

Upgraded L<IPC::Run> to 0.78, which is now pseudohash-free (later
versions of Perl complain). [Peter]

=item *

Moved htdocs/help/history.html to htdocs/help/log.html to correct links.
[Perrin]

=item *

Updated L<Imager> to 0.43. [Peter]

=item *

Updated L<HTTP::BrowserDetect> to the latest version, 0.98. [Peter]

=item *

Limited the directories being searched by C<bin/krang_install> when
looking to change execute permissions on a newly-installed backup
file.  There was no need to search a number of potentially large
directory trees, this should improve installation times. [Peter]


=item *

Added C<< published => 1 >> argument to L<Krang::Media> C<find()>
method.  Limits returning objects to those that have been published
before.

=back

=head2 v1.023 - August 31, 2004

=over

=item *

Fixed filenaming in C<krang_backup> to use the correct 2-digit month
(old month values were 00-11, not 01-12). [Peter]

=item *

Fixed a bug in L<Krang::Media> where thumbnails of certain images were
causing segfaults.  [Peter]

=item *

Fixed L<Krang::Story>->C<preview_urls()> to return the correct preview
URL for all sites when a story is associated with multiple sites.
[Peter]


=item *

Made L<Krang::Publisher>->C<additional_content_block()> a lot easier
to use from the developer perspective.  Rather than handling the
result of the call, everything is now handled internally.  Overriding
C<publish()> to use C<additional_content_block> is no longer required.
Additionally, it's backwards-compatible with the old way of doing
things, so no need to make changes to your element libraries.  [Peter]


=item *

Fixed symlink bug that caused thumbnails to disappear from the UI
after a Krang instance was moved to a different location on the
filesystem.  [Peter]

=item *

Fixed a bug where deleting a newly-copied story threw an error in the
UI. [Peter]

=item *

Added platform support for Gentoo release 1.5.2, thanks to a patch 
from Fred Moyer (fmoyer@plusthree.com) [Perrin]

=back


=head2 v1.022 - August 6, 2004

=over

=item *

Added support for passing a list of classes to Krang::Story->find().
[Sam]

=item *

Added support for C<publish_category_per_page()> in the publish
process.  This functionality allows element library developers to
generate category template output customized for each page in a
story. [Peter]

=item *

Fixed a bug where Krang::ElementClass would complain about a missing
template for a sub-element that wasn't actually needed. [Sam]

=item *

Fixed a bug related to the internal tracking of assets in
L<Krang::Publisher>.  This finishes up a minor restructuring that
ensures C<krang_publish> publishes each story/media object only once
during a publish run. [Peter]

=item *

Fixed a bug in C<krang_publish>.  When publishing with the
C<--site_id> argument, all media objects under that site are now
published, not just those media objects linked to stories. [Peter]

=item *

Cleaned up the code handling the management of internal asset lists in
L<Krang::Publisher>.  This code is used to ensure the same asset is
not published more than once during a publish run. [Peter]

=item *

Added support for searching on C<site_id> in Krang::Media->find().
[Peter]

=item *

Added C<publish_category_per_page()> to
L<Krang::ElementClass::TopLevel>.  This method will soon be used by
L<Krang::Publisher> to determine whether or not to publish category
elements once for each page in a story, or once for all pages in a
story.  [Peter]

=item *

Added automatic height and width data to the Default::image element. 
[Perrin]

=back

=head2 v1.021 - July 21, 2004

=over

=item *

Upped Apache timeout from 30 to 600.  30 seconds was too short to
preview some extremely large stories.  [Peter]

=item *

Errors writing to the filesystem while executing a preview/publish
through the Krang UI are now logged properly in C<logs/krang.log>.
Previously, they were only reported in user-friendly (as opposed to
admin-friendly) fashion to the UI.  [Peter]

=item *

Added indexes on the C<class> and C<published_version> columns in the
C<story> table.  This greatly speeds up searches against these fields.
[Sam]

=item *

Added new method C<use_category_templates()> to
L<Krang::ElementClass::TopLevel>.  This boolean method defaults to
true, and can be used to determine whether or not to wrap story output
in category templates. [Peter]

=item *

Fixed a bug which caused scheduler problems in upgraded Krang
installs.  Krang::Schedule::Daemon was missing code to reset
REMOTE_USER for each instance.  [Sam]

=item *

Added directory hashing to Krang::Media's XML serialization system.
This allows a single KDS file to contain any number of media files.
The previous limit was 32,000. [Sam]

=item *

Added C<no_parent> option to Krang::ListItem::find(). [Sam]

=item *

Fixed a bug in Krang::ListItem::find() which prevented C<ids_only>
from working. [Sam]

=item *

Added missing indexes to the list tables, providing an impressive
speedup in working on large lists. [Sam]

=item *

Fixed a bug that prevented Krang from installing on very recent MySQL
releases which do not tolerate trailing commas in C<CREATE TABLE>
statements. [Aaron Ross]

=item *

Added the ability to run Krang against a MySQL database on a different
machine.  There is a new configuration parameter, C<DBHost>, and a new
option to C<krang_install>, C<--DBHost>.  [Aaron Ross]

=item *

Fixed Krang::CGI::Publisher to not produce a nav-bar when preview
results in an error. [Sam]

=item *

Fixed Krang::User to not load Krang::Group unless it needs to interact
with groups.  This is needed because Krang::Script now uses
Krang::User to run as the 'system' user.  Loading Krang::Group will
cause Krang to load its element libraries, which isn't always a good
thing to do. [Sam]

=back

=head2 v1.020 - Jun 28, 2004

=over

=item *

Fixed bug in Krang::ElementClass::Date which prevented the default
method from returning the current date. [Sam]

=item *

Upgraded HTML::Template to the latest release, 2.7, to fix a bug where
a stale template could be returned from the cache under unusual
circumstances. [Sam]

=item *

Fixed a bug in the installer which prevented installing using an
element set contained within an add-on. [Sam]

=item *

Added the ability to pass a filename to Krang::ElementClass's
find_template() method.  [Matt]

=item *

Fixed a bug preventing deletions in the List Admin from working
correctly. [Matt]

=item *

Fixed a bug in the FedoraCore1 platform library that would fail to find
chkconfig unless it was in the user's PATH. [Sam]

=item *

Fixed a bug where elements using the default Krang::ElementClass
input_form() implementation would eventually cause browsers to slow to
a crawl and eventually crash.  The whole sordid tale is here:
http://perlmonks.org/index.pl?node_id=363214 [Sam]

=item *

Fixed a bug where clicking Publish on the Edit Media screen didn't
save changes. [Sam]

=item *

Fixed a bug where a story that failed to publish would still get a
'published' log entry.  [Sam]

=item *

Added support for Fedora Core 2. [Sam]

=item *

Fixed problem determining C<KRANG_ROOT> on Fedora Core 2 in all
Krang scripts. [Sam]

=back

=head2 v1.019 - Jun 04, 2004

=over

=item *

Fixed bug where C<krang_export> could only write output in directories
where C<KrangUser> had write permissions.  The output file is now
opened before su'ing to C<KrangUser>. [Sam]

=item *

Removed support for C<--append> from C<krang_export>.  This option was
never, to my knowledge, used and it didn't work after the permissions
fix above.  [Sam]

=item *

Changed the schema for the Krang::User XML format to make the new
'hidden' field optional.  This allows data files from pre-v1.017 Krang
to load in later Krangs. [Sam]

=item *

Fixed the v1.018 upgrade module to successfully upgrade instances from
v1.016 and older.  Also made changes to allow repeated runs of the
upgrade module to succeed even if the upgrade stops part way through.
[Sam]

=item *

Changed C<krang_upgrade> to wait till the upgrade is complete before
updating Krang's version number.  This means that failed upgrades can
be re-run and the same upgrade modules will be run again. [Sam]

=item *

Fixed Gentoo Platform tests so that any version of Gentoo 1.4.x now 
works. [Peter]

=item *

Fixed a bug in the error-handling section of Krang::Publisher that was
hiding the real cause of errors during publish.  [Peter]

=item *

Fixed broken --republish_only flag in bin/krang_publish. [Peter]

=item *

Changed the default of Krang::ElementClass::Date so that dates are updated 
when the default() method is called and not when new() is called.


=item *

Made Krang::Sotry::find(published=>1) work with stories that had a published 
version of 1/0 instead of NOT NULL / NULL.

=item *

Fixed Krang::XML::Writer to allow raw tabs in XML without Base64
encoding. [Sam]

=item *

Added a workaround for a very strange seg-fault bug.  [Sam]

=item *

Fixed bug where aftrer upgrading to v1.018 old users don't show up in
the User Admin list screen. [Sam]

=item *

Changed Krang::Site so that only the site's URL is required to be
unique.  Requiring all four fields to be unique, while seemingly
sensible, causes numerous problems during data imports.  If necessary
we could add these checks back in at the UI level in Krang::CGI::Site.
[Sam]

=item *

Fixed a bug in Krang::Contrib's full_name() that would add ", " to the
end of the name when the contributor had an empty suffix. [Sam]

=item *

Fixed a bug in Krang::Publisher where no file would be written if the
story's output contained only whitespace or was empty. [Sam]

=item *

Bugfix related to the publish changes made in 1.017 - assets linked to
a story being previewed from an edit interface are now marked
properly.  Media objects are now marked properly when previewed. [Peter]

=item *

Replaced Archive::Tar in Krag::DataSet->new with the system 'tar' for a 50x 
speedup in untaring. [Rudy]

=item *

Removed code from Krang::Contrib that disallowed stories with existing
historical contrib-contrib_type pairs to preview/publish. [Matt]

=back

=head2 v1.018 - May 10, 2004

=over

=item *

Fixed permissions error during upgrade backup creation. [Sam]

=item *

Fixed bug where permissions were not being applied to the Find Link
and Active list screens. [Sam]

=item *

Fixed a bug in Krang::Group which caused root-category permisssions to
be randomized during rebuild_category_cache().  [Sam]

=item *

Added C<--no-backup> option to C<krang_upgrade>. [Sam]

=item *

Fixed bug in C<bin/krang_publish> where unknown errors during story
publish would trigger an exit without any kind of useful message.  The
error is now printed to STDERR. [Peter]

=item *

Changed Krang to log and drop elements which exceed the maximum
allowed by their parent element.  This mirrors the behavior for
elements with illegal class names.  This allows for an easier element
set development process at the risk of possible data loss, which is
somewhat mitigated by the built in revision system. [Sam]

=item *

Fixed Krang::ElementLibrary to return a sorted list from top_levels().
This results in a sorted list or article types in the UI.  [Sam]

=item *

Added a new hidden user called 'system' which is now used by
Krang::Script.  This means you can now delete the 'admin' user with
impunity. [Sam]

=item *

Fixed bug where Krang::ElementClass::TopLevel::publish_check() was not
being checked by Krang::Schedule.  Stories that are marked to not be
published by the scheduler will now have their wishes respected.
[Peter]

=item *

Fixed bug where contributors created by C<krang_import> weren't
searchable in the UI unless they had first, middle and last
names. [Sam]

=item *

Added code to generate HTML documentation for the scripts in
F<bin/>. [Sam]

=item *

Fixed a bug where previewing/publishing zero-length stories caused an
error.  [Peter]

=back

=head2 v1.017 - April 29, 2004

=over

=item *

Fixed a bug where C<tmpl_include> calls in templates weren't correctly
searching the category tree in all cases. [Matt]

=item *

Modified Krang::Widget::category_chooser() to take into account
category permissions when building the category chooser.  Also took
advantage of the multiple-root support in HTML::PopupTreeSelect 1.4 to
remove to empty root node from the widget.  [Sam]

=item *

Upgraded HTML::PopupTreeSelect to the latest released version,
1.4. [Sam]

=item *

Fixed a bug in Krang::Group where the category permissions cache
wasn't being correctly rebuilt after group changes were saved. [Sam]

=item *

Added filesystem sanity checks to the Publish checks - If the
story/media object being tested does not exist on the filesystem in
all locations that it should, it's flagged for output, regardless of
versioning.  Also cleaned up some unneeded API cruft.  [Peter]

=item *

Large changes to the publishing engine.  When publishing/previewing a
story, Krang::Publisher will now check all related stories/media to
see if the most recent version of each object has been
published/previewed before.  If so, the object will not be
published/previewed again.  The chosen story/media object will always
be published/previewed.  This is only default behavior in the UI,
scheduled publish jobs and bin/krang_publisher still publish all
content.  Additional parameters have been added to the
Krang::Publisher API to support this functionality, see
L<Krang::Publisher> for more information.  [Peter]

=item *

Fixed bug in Krang::Contrib where importing a contributor with no
first name or no last name would duplicate the contributor if it
already existed instead of updating. [Sam]

=item *

Added the C<--skip> option to C<krang_import> which exposes the
existing Krang::DataSet::import_all() C<skip_classes> option from the
command-line. [Sam]

=item *

Removed "Delete Checked" button from List Admin screen.  Lists cannot
be deleted. [Sam]

=item *

Added Krang::Story->preview_version(), Krang::Media->preview_version
and Krang::ElementClass::TopLevel->force_republish() in anticipation
of forthcoming improvements to the publishing system. [Peter]


=item *

Upgraded XML::Validator::Schema to the latest release, 1.06. [Sam]

=item *

Fixed Krang::Story->preview_path() to use the submitted category
argument.  This was keeping preview from writing out content to
multiple sites. [Peter]

=item *

Added password-length check to My Preferences, enforcing the
6-character minimum length on passwords that exists everywhere else in
the UI.  [Peter]

=item *

Fixed error reporting in the publish process - error messages are
displayed in a more user-friendly fashion.[Peter]

=item *

Fixed Krang::ElementClass->publish() to trap errors thrown by
HTML::Template::Expr->output(), and fixed Krang::CGI::Publisher to
properly report errors and not try to redirect users when failures
occur in preview.  [Peter]

=item *

Fixed krang_ftpd to setup higher file and memory limits.  These limits
were preventing the FTP server from operating on some systems. [Sam]

=back

=head2 v1.016 - April 20, 2004

=over

=item *

Fixed Krang::DB to always turn on mysql_auto_reconnect (it was already
on by default under mod_perl).  This should prevent the schedule
daemon from periodically dying when a database connections times out.
[Sam]

=item *

Fixed bug in Krang::ElementClass which would fail to setup
"is_$element" template vars if "$element" wasn't used as a template
var itself. [Matt]

=item *

Changed site editor to allow colons so that port numbers can be
specified for preview URLs. [Perrin]

=item *

Synchronized Devel-StackTrace with latest from CPAN, so that we are
now using the standard release. [Perrin]

=item *

t/group.t now uses Krang::Test::Content to generate random content,
rather than bin/krang_floodfill. [Peter]

=item *

More comprehensive FreeBSD support.  Krang now works on FreeBSD 4.9
and 5.2.1, and should work on versions between and previous to that
(as long as the appropriate dependencies are in place).  [Peter]

=item *

ftpserver.t now uses Krang::Test::Content.  Simplifies cleanup, and
fixes a bug where ftpserver tests would fail if krang_install used the
--AdminPassword argument (a user is now created for the purposes of
testing). [Peter]

=item *

Added Krang::User creation/destruction to Krang::Test::Content -
furthering the goal that Krang::Test::Content should be able to create
all parts of a site randomly, and clean up everything properly at the
end. [Peter]

=item *

Modified Krang::Contrib::deserialize_xml() to create contributor types
as needed.  [Sam]

=item *

Changed Krang::ElementClass::Date to store and load data in XML using
an ISO-8601 date-time format. Also added missing template_data()
method.  [Sam]

=item *

Added support for Debian. [Jason Purdy]

=item *

Fixed bug where clicking on a media link in the element editor would
open a new window every time. [Sam]

=item *

Moved code to run tests from Makefile into bin/krang_test.  This
allows krang_install to affect which Perl binary runs the tests. It
also helps with BSD portability since the test target didn't work with
BSD make. [Sam]

=back

=head2 v1.015 - April 8, 2004

=over

=item *

Added a message to remind users that they must create a site before
adding stories, media or templates. [Sam]

=item *

Added initial support for FreeBSD!  Currently it only supports FreeBSD
5.2.1 with GNU make (gmake) installed, as that was the only available
testable environment.  Would be nice if someone with more experience
in BSD Makefiles could get Krang's Makefiles to work with BSD make.
There should be nothing keeping Krang from working with earlier
versions of FreeBSD, but that will require someone to pick up the BSD
ball and run with it.  [Peter]

=item *

Fixed site editor to check that URLs don't have paths attached to them
and that paths are obsolute. [Sam]

=item *

Fixed krang_upgrade to use Krang::Platform.  Added a new method to
Krang::Platform, post_upgrade_message(). [Sam]

=item *

Upgraded XML-Writer, HTML-Parser, and Tar-Archive to get rid of warnings.
[Perrin]

=item *

Upgraded mod_perl and apache to latest releases. [Perrin]

=item *

Fixed the behavior of Krang::Publisher->preview_story().  Following
the original spec, it now writes the story out to all categories in
the preview path.  Fixed Krang::Story->preview_path as well. [Peter]

=item *

Upgraded Test::Harness to 2.40 to enable warnings during tests.  Fixed
a number of warnings in the test files. [Perrin] [Sam]

=item *

Fixed bug where schedule tests would fail frequently due to
krang_schedulectl leaving bad PID files around.  Also made the
schedule tests quiet unless an error occurs. [Sam]

=item *

Fixed a bug where using a category_trail_loop in a category element
template produced an ISE. [Sam]

=item *

Added support for Fedora Core 1. [Perrin Harkins]

=item *

Moved Krang user/group creation from krang_install to Krang::Platform.
This can now be overridden on a platform-by-platform basis. [Peter]

=item *

Created Krang::Platform->find_bin().  Use of this sub now needs to be
propegated throughout krang_install along with Krang::Platform and its
derivatives - it searches $PATH for the full path for the executable
you're trying to run. [Peter]



=item *

Moved the final installation message out of bin/krang_install, created
Krang::Platform->post_install_message() that generates the same output.
This can now be overridden & extended on a platform-specific basis. [Peter]

=item *

Split the various checks out of Krang::Platform->verify_dependencies().
This will simplify ports to other platforms, as individual checks can
now be overridden, rather than the entire sub. [Peter]

=item *

Added new default scheduled job to analyze DB tables nightly.  This
greatly improves performance for large databases. [Sam]

=item *

Fixed bug where default scheduled jobs (tmp cleaner and session
expiration) weren't being run for new installations. [Sam]

=item *

Fixed krang_createdb to stop after the first failed system
call. [Scott Lanning]

=item *

Added enhanced cache debugging code and a last-resort check in an
Apache log_handler to make sure the cache is off at the end of the
request. [Sam]

=item *

Moved setup of /etc/init.d link from krang_install into the Redhat
platform modules' finish_installation() methods.  This should allow
the Gentoo and Debian ports to proceed. [Sam]

=item *

Fixed build and installation system to work with a Perl that isn't
called 'perl' and in your path.  So, for example, if you've got a
binary called 'perl5.8.0' you can build Krang with it and install with
it. [Sam]

=item *

Added initial support for Gentoo 1.4.3. [Peter]

=item *

Updated porting.pod with steps that might really work. [Sam]

=item *

Fixed a bug where an error occuring during preview triggered a
Krang::Cache error which corrupted the display. [Sam]

=item *

Improved error message generated when InstanceElementSet is set to an
element set that isn't installed. [Peter]

=item *

Fixed a ton of whitespace in module source files which was breaking
the POD output. [Peter]

=back

=head2 v1.014 - March 31, 2004

=over

=item *

First public release of Krang!

=back
