=head1 Krang Configuration

Krang is configured through a single configuration file called
F<krang.conf>.  This file is stored in the F<conf/> directory inside
Krang.  Krang's configuration file is in the same format as Apache.
Simple directives are set using the name and value, separated by a
space.  For example:

  ApachePort 8000

Multiple values are separated by spaces.  Example:

  ParentSets Flex Default

If a value contains a space, it must be enclosed in quotes (single or
double):

  InstanceDisplayName "MotorTrendPIRT/CMS, Ultra Super Edition"

Instance blocks in Krang work like VirtualHost blocks in Apache.  For
example, the instance called "truckin" would have a block like:

  <Instance truckin>
     InstanceDBName truckin
     InstanceHostName cms.truckin.com
     # ...
  </Instance>

Just like Apache, configuration directives defined outside the
C<Instance> blocks are inherited by the instances.  This means that
common settings can be defined globally and then selectively
overridden inside the Instance blocks, reducing overall configuration
size.

The actual configuration directives used to configure Krang are
documented inside the C<krang.conf>.

B<NOTE:> After you edit F<krang.conf> don't forget to restart Krang
so your changes can take effect:

  bin/krang_ctl restart


