
=head1 Installing PIRT CMS 2.0 (Krang)

The following instructions will install Krang on a RedHat Linux 7.3 or
Redhat Linux 9 system, on the i686 architecture.

To install, do the following as root:

  # cd <Krang src directory>
  # ./bin/krang_install \
         --HostName             $HostName            \
         --IPAddress            $IPAddress           \
         --AdminPassword        $AdminPassword       \
         --DBUser               $DBUser              \
         --DBPass               $DBPass              \
         --InstanceDBName       $InstanceDBName      \
         --InstanceHostName     $InstanceHostName    \
         --InstanceElementSet   $InstanceElementSet  


=head1 Install Worksheet

Before you install you must gather the following information.  The
following variables should be replaced in example shell commands with
the appropriate values.



=head2 Required Variables


=over 4

=item HostName

Host name used for CMS Apache virtual host (e.g., "cms23.thepirtgroup.com").


=item IPAddress

IP address used for CMS Apache server and FTP server.


=item AdminPassword

Password assigned to the "admin" CMS user (e.g., "shredder").


=item DBUser

Name of MySQL user which is used by this CMS instance (e.g., "motortrend").



=item DBPass

MySQL user password which is used by this CMS instance (e.g., "xyzzy").



=item InstanceDBName

Name of MySQL database which is used by this CMS instance (e.g., "motortrend").



=item InstanceHostName

Host name of CMS virtual Apache server (e.g., "cms.motortrend.com")


=item InstanceElementSet

Name of element set used by this CMS instance (e.g., "Flex").

=back




=head2 Optional Variables

=over 4

=item MySQLRootPassword

Defaults to "" (none).  The password for the MySQL user "root" who is
assumed to exist, and to have full access to MySQL.


=item InstallPath

Defaults to "/usr/local/krang".  Directory into which Krang should be installed.


=item KrangUser

Defaults to "krang".  UNIX user for process ownership (Apache, etc.), file ownership and
install location.


=item KrangGroup

Defaults to "krang".  UNIX group for process ownership (Apache, etc.), file ownership and
install location.


=item FTPPort

Defaults to 21.  Port on which FTP server should run.


=item ApachePort


Defaults to 80.  Port on which CMS Apache server should run.


=item SMTPServer

Defaults to localhost (127.0.0.1).  Address of SMTP mail server used
by Krang for sending email.


=item InstanceDisplayName

Defaults to $InstanceHostName.  Name of the Instance, displayed on
the CMS interface for informational purposes.

=item WithAddon

This option provides an addon which will be installed with Krang.
Krang addons can provide element sets, libraries and other services.
You can specify multiple addons to install.

=back



=head2 Some definitions


=over 4

=item Installation

A particular version of Krang installed on a server.  A single host
server may have multiple installations, but this would be rare
outside of development.  A single installation may have multiple
"Instances".


=item Instance

A particular CMS database and element set.  Multiple instances may
exist within a particular Krang installation.  A single instance may
have multiple "Sites".


=item Site

A website managed by Krang.  Multiple sites may exist
within a particular Krang instance.  Unlike Installations and
Instances, Sites are not installed via this installation process.
Sites are configured from the Krang web interface.

=back


