=head1 Krang Paper Prototype Screen List

This document lists all screens that will be subject to paper
prototyping.  In some cases an item in the list will result in more
than one screen, but in most cases there will be a one-to-one
correspondence.  Items in the list marked "[not in bric]" are entirely
new in Krang.  Otherwise, the existing Bricolage screen will be
captured and linked off this document in a future revision.

=over

=item Media

=over

=item New

=item Edit

=item Edit, Notes

=item Edit, Trail

=item View

=item Find, Simple Search

=item Find, Advanced Search

=item Bulk Upload

=back

=item Story

=over

=item New (Flex Article)

=item Edit, First Screen (Flex Article)

=item Edit, Page Element (Flex Article)

=item Edit, Bulkedit Paragraphs (Flex Article)

=item Edit, Adding Media (Flex Article)

=item New (Flex Cover)

=item Edit, First Screen (Flex Cover)

=item Edit, Column (Flex Cover)

=item Edit, Adding a Lead-in (Flex Cover)

=item Edit, Keywords

=item Edit, Contributors

=item Edit, Schedule [not in bric]

=item Edit, Notes

=item Edit, Trail

=item View

=item Find, Simple Search

=item Find, Advanced Search

=back

=item Templates

=over

=item Edit

=item View

=item Find, Simple Search

=item Find, Advanced Search

=back

=item Workflow

=over

=item My Workspace

=item My Preferences [not in bric]

=item My Alerts

=item Edit Desk

=item Publish Desk

=item Publish Screen

=back

=item Admin

=over

=item Global Preferences

=item User List

=item User Add

=item User Edit

=item User Group List

=item User Group Add

=item User Group Edit

=item Contributor List

=item Contributor Add

=item Contributor Edit

=item Category List

=item Site List [not in bric]

=item Site Add [not in bric]

=item Site Edit [not in bric]

=item Category Add

=item Category Edit

=item Scheduled Jobs

=back

=item Misc.

=over

=item Navigation

=item Category Picker

=back

=back

