=head1 Krang Performance Tests

=head2 Introduction

This document provides the results of performance tests performed on
Krang v0.018.

These tests were run on a dual-P4/2.8Ghz machine with 4GB of RAM
running Redhat Linux 7.3.

The content used in the tests was randomly generated to simulate the
contents of a typical Krang instance.  The content used is similar to
that generated with the krang_floodfill script included with Krang.

=head1 Tests

=head2 Light Load

This system is similar to many small websites which will run Krang.

  Sites:        1
  Categories:   10
  Stories:      3,000
  Media:        5,000
  Contributors: 50

Results:

  Story Publish:                3 per second 
  Total Site Publish:           15 minutes
  Media Upload and Save:        151 per second
  Story Import:                 9 per second
  Story Find Time (by title):   .025  seconds
  Find Media, limit 100:        .025 seconds    

=head2 Medium Load

This system has as much content as the largest sites currently running
in our organization.

  Sites:        3
  Categories:   300
  Stories:      10,000
  Media:        50,000
  Contributors: 500

Results:

  Story Publish:                3 per second
  Total Site Publish:           65 minutes
  Media Upload and Save:        139 per second
  Story Import:                 7 per second
  Story Find Time (by title):   .15  seconds
  Find Media, limit 100:        .025 seconds

=head2 High Load

This system contains enough content to publish several very large sites.

  Sites:        20
  Categories:   2,000
  Stories:      100,000
  Media:        500,000
  Contributors: 5000

Results:

  Story Publish:                3 per second
  Total Site Publish:           15 hours, 24 minutes
  Media Upload and Save:        42 per second
  Story Import:                 7 per second
  Story Find Time (by title):   4.6  seconds
  Find Media, limit 100:        .025 seconds

