=head1 Releasing Krang

This document describes how to make a new release of Krang within
PIRT.

=head2 Release Checklist

=over 4


=item Make sure your CVS working directory is up to daye (C<cvs update -d>)

=item Update $VERSION in Krang.pm and commit change to CVS


=item Verify that upgrade modules have been created for this release

=over 4

=item Located in F<KRANG_ROOT/upgrade/>

=back


=item Run C<bin/krang_makedist>

=over 4

=item Will create release file in KRANG_ROOT, "krang_V1_2.tar.gz"

=back


=item Test release on separate machine

=item Release to PIRT for production


=back


