=head1 Releasing Krang

This document describes how to make a new release of Krang within
PIRT.

=head2 Release Checklist

=over 4


=item Make sure your CVS working directory is up to date (C<cvs update -d>)

=item Update $VERSION in Krang.pm

=item Verify that upgrade modules have been created for this release

=item Make sure all changes are committed to CVS.

=item Run C<bin/krang_makedist>

=item Test release on separate machine

=item Release to PIRT for production


=back


=head2 What release will do

=over 4

=item Tag CVS

Based on the version in Krang.pm, all the files in the release will be
tagged.  Tag names are derived from the version number by replacing
"." with "_", and pre-pending a "V", e.g., 

  Version: 1.23
  CVS Tag: V1_23

If you forget to update the $VERSION in Krang.pm, the release system
will detect that the tag already exists and will abort.


=item Create tar-ball


=back


