=head1 Krang Todo List

The following are bugfixes/enhancements in Krang that we're looking to
address.  If there are more items that should go on the list, if you
want to help, let us know!

=head2 HTML-Only Items

These issues are entirely in the UI, and can be addressed by
knowlegable HTML people, without any interaction with perl code.

=over

=item Changes to Save functionality (1.101?)

To help prevent lost saves, the message in the JavaScript window should
say:

  "Save Changes to Story?"

There will be 3 options:

=over

=item 1 Yes

Yes, will save the changes and send you to the desired page.

=item 2 No

No, will not save the changes and send you to the desired page.

=item 3 Cancel

Cancel, will not save changes and you will remain on the same page

=back

=back

=head2 HTML/Perl Items

These items are UI issues, but require changes to the underlying Perl
code to make them happen.

=over

=item New Template - Element Chooser (1.200?)

When creating a new template - the element chooser pulldown is nearly
useless - it doesn't offer any concept of context.

The pulldown should be replaced with a Category-Chooser-style Element
Chooser, one that shows the hierarchtical relationships between
elements.  The current category chooser (built by L<Krang::Widget>)
can be used as a guide.

=item Template UI - variable browser (1.200?)

One of the hardest parts of template development in Krang is that the
CMS provides no way for template developers to see what variables are
available to them, or what their makeup is.

Some kind of element-variable browser would be extremely helpful.  How
it looks and how the user interacts with it still needs to be
determined, but something useful should be possible.



=item Fixing Stylesheet issues in the Krang UI/Making Krang resizeable (1.200?).

At the moment, the Krang UI is fixed at 800 pixels wide, and has
chunks that make it incompatible with certain browsers (IE 5 on the
Mac is one example).

There are a number of flaws in Krang's HTML/CSS that need to be
corrected - some are template-based, others are in the HTML built by
various perl modules (L<Krang::Pager> for one).

The final goal would be a cleaner HTML/CSS implementation of the UI
that would support more browsers and be easier to maintain and skin in
the long run.

=back

=head2 Dev-only Items

The following are perl-only issues.

=over

=item New Story - Story Type pulldown should be alphabetized.

The Story-Type pulldown should be in alphabetical order.

=item System Administrator Functions

=over

=item Full publish via Krang Scheduler (1.101?)

Allow Krang Scheduler to specify C<site_id> or C<category_id> for
scheduled publish.

=item krang_publish Enhancements (1.101?)

Allow the C<--media-only> option to work in conjunction with the
C<--site_id> option and publish only media in that site.

=back


=item Krang::ElementClass::HTMLArea (1.10x?)

Adding a new elementclass of HTMLArea.  Behavior would be akin to
Krang::ElementClass::TextArea, but it would use
HREF[HTMLArea|http://www.dynarch.com/projects/htmlarea/] to give
developers a limited (but configurable by element developers) set of
HTML widgets for formatting.


=item FTP Publish (1.200?)

Sending preview/publish output to a remote FTP server.


=item Default fill_template() capability (1.027?  1.028 more likely)

L<Krang::ElementClass>->fill_template() will be expanded to make it
possible to populate an element's template with all children down to
an arbitrary depth.

=item Cleaning MD5 Salt issues (1.200?).

The MD5 Salt should be built at install.  Care is needed to make sure
this doesn't break existing installs on upgrade.


=back

=head2 Other

Everything Krang-related that's not part of the application itself.

=over

=item * The Website

The current Krang website was put together in about 15 minutes,
perhaps less.  It needs a redesign.  Getting rid of the IFrames would
be a nice start.

A long-term goal would be the eat-your-own-dogfood goal - the site
should be managed by Krang.  Two major components are needed:

=over

=item 1

An element library & templates to serve the site

=item 2

A script to take Krang POD (both in /lib and /docs) and add it to the
site - the element library would need a good 'POD Article' story type.

=back

Publish-to-FTP functionality (see above) would also be helpful here.

=item * Documentation

Krang is still missing some key documentation.  The biggest hole is a
real user guide, something that could be handed to non-technical users
to help them use the site.


=back

